export { Button, Input, Textarea, Card, Modal, Loading, Skeleton, Toast, useToast } from '@/shared/ui';
export { SlideStatusBadge as StatusBadge } from '@/entities/slide/ui/SlideStatusBadge';
export { ContextualSlideStatusBadge as ContextualStatusBadge } from '@/entities/slide/ui/ContextualSlideStatusBadge';
export { ConfirmDialog, useConfirm } from '@/shared/ui';
export { ReferenceFileCard } from './ReferenceFileCard';
export { ReferenceFileSelector } from './ReferenceFileSelector';
export { FilePreviewModal } from './FilePreviewModal';
export { ReferenceFileList } from './ReferenceFileList';
export { AppFooter as Footer } from '@/widgets/app-footer/ui/AppFooter';
export { Markdown } from '@/shared/ui';
export { AiRefineInput } from './AiRefineInput';
export { ShimmerOverlay } from '@/shared/ui';
export { ImportMarkdownModal } from './ImportMarkdownModal';
export { CreationGuideDialog as HelpModal } from '@/features/deck-create/ui/CreationGuideDialog';
export { DeckSettingsDialog as ProjectSettingsModal } from '@/features/deck-workspace/ui/DeckSettingsDialog';
export { ExportActivityPanel as ExportJobsPanel } from '@/entities/export/ui/ExportActivityPanel';
export { AccessGate as AccessCodeGuard } from '@/app/AccessGate';
export { TextStyleSelector } from './TextStyleSelector';
export { Pagination } from '@/shared/ui';
